### ISSUE TITLE
Permission denied when installing package

### ISSUE THREAD

**Issue by dflemstr** [borgfriend/gatsby-remark-embed-video#5] opened 2018-05-09 20:32 UTC
The package archive for this library (as published on NPM) cannot be unpacked, because its contents are as follows:

```shell
$ tar tvf gatsby-remark-embed-video-1.2.0.tgz
drw-rw-rw- 0/0               0 2018-04-20 10:09 package
-rw-rw-rw- 0/0             855 2018-04-20 09:52 package/CHANGELOG.MD
-rw-rw-rw- 0/0            3835 2018-04-20 10:10 package/index.js
-rw-rw-rw- 0/0            3201 2018-04-20 10:09 package/index.ts
-rw-rw-rw- 0/0             868 2018-04-20 10:10 package/package.json
-rw-rw-rw- 0/0            1486 2018-03-29 23:42 package/readme.md
-rw-rw-rw- 0/0            5197 2018-04-20 10:09 package/tsconfig.json
```

When running `yarn add`, this is the output:

```
10:25:05 PM: error An unexpected error occurred: "https://registry.yarnpkg.com/gatsby-remark-embed-video/-/gatsby-remark-embed-video-1.2.0.tgz: EACCES: permission denied, open '/opt/build/.yarn_cache/npm-gatsby-remark-embed-video-1.2.0-c38dd6a6055c9c1a2e02937cf95d2eed3a5201cf/CHANGELOG.MD'".
10:25:05 PM: info If you think this is a bug, please open a bug report with the information provided in "/opt/build/repo/yarn-error.log".
10:25:05 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The reason is that there is an entry for the `package` directory with `rw` permissions only.  The directory needs to have `rwx` permissions (execute bit means that a directory is browsable in UNIX) or not even be in the tar archive to begin with.  Compare with the `lodash` package:

```shell
$ tar tvf lodash-4.17.10.tgz                                   
-rw-r--r-- 0/0             662 1985-10-26 09:15 package/package.json
-rw-r--r-- 0/0             714 1985-10-26 09:15 package/_apply.js
-rw-r--r-- 0/0             684 1985-10-26 09:15 package/_arrayAggregator.js
-rw-r--r-- 0/0             537 1985-10-26 09:15 package/_arrayEach.js
-rw-r--r-- 0/0             528 1985-10-26 09:15 package/_arrayEachRight.j
```

Note that there is no entry for `package`!

**Comment by borgfriend** [comment] 2018-06-15 22:42
Sorry, I could not reproduce your issue.

I added the package using yarn. (`yarn add`) and could be used as expected.

I tried fetching the package via:
`npm pack gatsby-remark-embed-video`
`tar tvf gatsby-remark-embed-video-1.4.0.tgz`
It could be unpacked without issue.

Has your issue been resolved?

**Comment by dflemstr** [comment] 2018-06-17 19:55
@borgfriend no, this still happens.  Are you maybe using an operating system that doesn't check permissions (like Windows or some configurations of OS X?)

**Comment by borgfriend** [comment] 2018-06-17 20:20
I tested this on elementaryOS (based on Ubuntu) - and did not encounter this issue.
Windows of course does not care about that. I currently do not have an OSX to test.

I suppose running `chmod +rwx` would solve the issue?

**Comment by dflemstr** [comment] 2018-06-25 22:52
Somehow this stopped happening on my local computer, but keeps happening on netlify.  I will investigate more.

**Comment by borgfriend** [comment] 2018-12-20 16:45
Closing Issue, as I cannot reproduce it, and no additional information was provided.

**Closed by borgfriend** 2018-12-20 16:45 UTC
